name: update personal blog
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install markdown and beautifulsoup
        run: |
          python -m pip install --upgrade pip
          pip install markdown
          pip install beautifulsoup4

      - name: run script
        run: |
          python blog/update-blog.py $(TZ=Europe/Moscow date +%d/%m/%y)

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: .
