name: update personal blog
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install markdown and beautifulsoup
        run: |
          python -m pip install --upgrade pip
          pip install markdown
          pip install beautifulsoup4

      - name: run script
        run: |
          python blog/update-blog.py $(TZ=Europe/Moscow date +%d/%m/%y)

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes exist, committing and pushing"
            git commit -am "update blog"
            git push
          fi
